version: "3.7"

services:
  qg-business-mock-server:
    image: mockoon/cli:latest
    command: ["--data", "data", "--port", "3001"]
    ports:
      - "31001:3001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/api/healthcheck || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
    volumes:
      - ./mockoon-mocks.json:/data:ro
